### ISSUE TITLE
Breaking change in 1.2.1

### ISSUE THREAD

**Issue by schmee** [gorillalabs/sparkling#17]
When upgrading from 1.1.1 to 1.2.1 I had to explicitly require `sparkling.serialization` in my code. Technically, I suppose this constitutes a breaking change, and thus the version should be 2.0.0 and not 1.2.1. 

Technicalities aside, the only way I could find this out was to read the [comments in the source code](https://github.com/gorillalabs/sparkling/blob/master/src/clojure/sparkling/conf.clj#L82). I think this should be noted in the change log and also included somewhere in the guides.

**Comment by chrisbetz** [comment]
Hi,

sorry, this shouldn't have happened. I've tested with the sparkling-getting-started repo and it didn't appear there, so I was confident that it fixed all places where requiring sparkling.serialization was required before releasing.

Anyway: I'll try to fix that in 1.2.2, because it shouldn't be a breaking change. Could you please send me a little more detail on when that happened? Did you "lein repl" your project with a local spark master, "lein test" or did you "lein uberjar" and submitted it to a cluster?

Happy hacking

Chris

**Comment by chrisbetz** [comment]
Oh, sorry, found the glitch in getting started: I added it not to source but to :aot in project.clj:
            :aot [#".*" sparkling.serialization sparkling.destructuring]

I will add this to the documentation. For now, I'll add it to the readme.

**Comment by schmee** [comment]
Ahh, I thought having `:aot :all` would have the same effect! If I use your variant it works without any extra requires. Thanks for the quick response, keep up the great work!

**Comment by chrisbetz** [comment]
Yes, thought so too. But again, sorry for causing you trouble.
