### ISSUE TITLE
spark/map over sql dataset

### ISSUE THREAD

**Issue by NonaryR** [gorillalabs/sparkling#66]
Hello! I was wondering - how can I implement `spark/map` function over SQL dataset/dataframe?
Today I'm converting dataframe to json-rdd, and it is huge overhead.
Thank you!

**Comment by retnuh** [comment]
It's been awhile since I've done anything like this, and I don't think Sparkling has any specific support around this, but have a look at "User Defined Functions" (or UDF) for doing like map-like functionality on a dataframe.  There's plenty of blog articles, tutorials, etc.  Roughly, you register a UDF, and then do a select on the DF with your UDF to create a new column.  There are limitations on the cardinality of things, though.
